### ISSUE TITLE
Were you able to reproduce MemAE on KDD dataset?

### ISSUE THREAD

**Issue by bhatiasiddharth** [h19920918/memae#1]
Hi, thanks for sharing your code. Can you please tell if you were able to reproduce the MemAE results on the KDD dataset?

**Comment by h19920918** [comment]
I'm sorry about the late response. 

Unfortunately, I'm not work on now for this.

I'm not sure, you might change your backbone network for using those features in the KDD dataset. (I've never seen this dataset before, so I found it myself.)
The other things such as the memory component and KLD will be same as the original paper.

I recommend that you adopt the main components in my code and can implement yourself.
As I know, the authors have provided the official code.
Didn't they include the implementation result on the KDD dataset?
